name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # semver tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.6'

    - name: Install dependencies
      run: go mod tidy

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/shadcn-vanilla ./cli
        GOOS=linux GOARCH=arm64 go build -o dist/shadcn-vanilla-linux-arm64 ./cli
        GOOS=darwin GOARCH=amd64 go build -o dist/shadcn-vanilla-darwin-amd64 ./cli
        GOOS=darwin GOARCH=arm64 go build -o dist/shadcn-vanilla-darwin-arm64 ./cli
        GOOS=windows GOARCH=amd64 go build -o dist/shadcn-vanilla.exe ./cli

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload release assets (linux amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/shadcn-vanilla
        asset_name: shadcn-vanilla-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload release assets (linux arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/shadcn-vanilla-linux-arm64
        asset_name: shadcn-vanilla-linux-arm64
        asset_content_type: application/octet-stream

    - name: Upload release assets (darwin amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/shadcn-vanilla-darwin-amd64
        asset_name: shadcn-vanilla-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload release assets (darwin arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/shadcn-vanilla-darwin-arm64
        asset_name: shadcn-vanilla-darwin-arm64
        asset_content_type: application/octet-stream

    - name: Upload release assets (windows amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/shadcn-vanilla.exe
        asset_name: shadcn-vanilla-windows-amd64.exe
        asset_content_type: application/octet-stream

